### ISSUE TITLE
java.io.IOException: error=2, No such file or directory

### ISSUE THREAD

**Issue by grvhi** [awslabs/amazon-kinesis-client-python#1]
@knorwood - Firstly, thanks for getting this out! Really great stuff.

I've hit a small issue in that java can't find my program:

`java.io.IOException: Cannot run program "consumers.py": error=2, No such file or directory`

I've set the `executableName = consumers.py` in my properties file. Is that path relative to dir in which I'm running the command? Or is absolute? (I've tried both, with no luck).

Also, I can't seem to find much on the recommended way to daemonize the process?

Thanks!

**Comment by venkat-vs-id** [comment]
I got the same problem and this is what I found

http://venkat-echo.blogspot.com.au/2015/01/kinesis-trouble-shooting.html

1) you can have absolute path or relative it doesnt matter.
2) it is not necessary to set the PATH if you are using absolute path
3) if you had use the (consumer)sample.py as a template, then fix the shebang (ie.. origina sample.py had #!env python... It is for this the KCL lib threw the error file or directory not found. change this to the actual python path like (#!/usr/bin/env python). Then the file or folder not found error is gone.
