### ISSUE TITLE
Update to latest version of Java Client

### ISSUE THREAD

**Issue by markstephens** [awslabs/amazon-kinesis-client-python#15]
Hi

Can you update to the latest version of the [KCL Java Client](https://github.com/awslabs/amazon-kinesis-client#release-160-july-31-2015) - version 1.6.0? It has some useful features.

Thanks,
Mark

**Comment by manango** [comment]
@markstephens, Python KCL (1.2.0) has been updated to use the latest Java KCL.

**Comment by markstephens** [comment]
Thank you @manango!
