### ISSUE TITLE
record does not have 'approximateArrivalTimestamp' field

### ISSUE THREAD

**Issue by haje01** [awslabs/amazon-kinesis-client-python#18]
When `process_records` receives records, each record does not have `approximateArrivalTimestamp` field, which is what I need to sort messages in order.

Java KCL 1.6.1 support it: https://github.com/awslabs/amazon-kinesis-client

**Comment by zdjohn** [comment]
same here. do i need to update producer's code in order to start having "approximateArrivalTimestamp" shown?

**Comment by pfifer** [comment]
I'll be updating the python library to use 1.6.4 of the KCL, and at the same time intend to add the aproximateArrivalTimestamp.

**Comment by pfifer** [comment]
I've complete the major code changes to add the new features.  I need to conduct some more testing, and am undergoing an internal code review of the changes.  

For those that are curious the changes are on my fork 
https://github.com/pfifer/amazon-kinesis-client-python/tree/upd-features

These changes are dependent on some additional feature changes on the Java side as well: https://github.com/pfifer/amazon-kinesis-client/tree/mld-update

**Comment by whummer** [comment]
@pfifer The changes in the upd-features branch look very promising. Especially adding support for `approximateArrivalTimestamp` is critical. Any estimates as to when we can expect to see this released? Thanks

**Comment by pfifer** [comment]
This is now available on PyPI.
