### ISSUE TITLE
Bump to KCL v1.6.2

### ISSUE THREAD

**Issue by evnm** [awslabs/amazon-kinesis-client-python#20]
v1.6.2 of the Java Kinesis client was published [a few weeks ago](https://github.com/awslabs/amazon-kinesis-client/commit/74c259ca1182dffa05fec6edf307f53429d39f62). Would be good to bump the Python library.

**Comment by pboocock** [comment]
+ 1

KCL 1.6.2 fixes two big issues we've been having trouble with. Would be great to have it required natively in the kclpy so we don't have to manually upgrade KCL.

**Comment by jacobliuat** [comment]
+1

**Comment by pnorth423** [comment]
+1 
KCL 1.6.2 fixes some nasty NPE. I wonder if simply replacing the 1.6.1 .jar file with the 1.6.2 one will work in the meantime, lets find out heh : p

**Comment by whummer** [comment]
+1 upgrade to KCL 1.6.2 is critical, would be highly appreciated. thanks!

**Comment by pfifer** [comment]
Just to let everyone know we are aware of this, and are tracking it.

**Comment by pfifer** [comment]
I've just release 1.6.4 of the KCL, and am starting on updating the python library to use 1.6.4.

**Comment by pfifer** [comment]
Just release the version of the amazon-kinesis-client-python that uses 1.6.4.  Sorry for the delay in getting it out.
