### ISSUE TITLE
Update aws-java-sdk to V1.11.28

### ISSUE THREAD

**Issue by timmartin19** [awslabs/amazon-kinesis-client-python#27]
They are sadly behind and I need the `ContainerCredentialsProvider` which is not available in the version specified.

https://github.com/awslabs/amazon-kinesis-client-python/blob/master/setup.py#L55

Is there another mechanism for manually setting the version for those packages?  It would be very helpful.

**Comment by pfifer** [comment]
There isn't currently a direct way to do that, but it should be safe to directly replace the aws-java-sdk-core.jar with an updated version.  The change would need to be made to the egg where it's installed.  I'm considering making a different way to handle the Java components of this, that would allow more direct control of the dependencies.

**Comment by pfifer** [comment]
Unfortunately this didn't make it for the most recent release.  I need to adjust the dependency resolution of the [Kinesis Client Library](https://github.com/awslabs/amazon-kinesis-client) to use the range syntax.  I'll look at doing this for an upcoming release of the KCL.  The way this library works would always be a bit restrictive

There are alternate methods that I could use for launching the MultiLangDaemon.  These methods would significantly increase flexibility, but would require the use of Maven to create the initial bootstrap scripts.  I'm curious to know what the feelings people would have on use Maven with this library?

**Comment by pfifer** [comment]
Fix is in [KCL #126](https://github.com/awslabs/amazon-kinesis-client/pull/126)

**Comment by pfifer** [comment]
Version 1.4.4 is now available that includes version 1.11.115 of the AWS Java SDK.

Feel free to reopen if you're still having a problem.
