### ISSUE TITLE
Bump to KCL v1.6.5+

### ISSUE THREAD

**Issue by whummer** [awslabs/amazon-kinesis-client-python#32]
v1.6.5+ of the KCL contains a number of important changes (e.g., changes to LeaseManager, updated code for approximateArrivalTimestamp). Can we expect to see a new release of the python library soon? Thanks
https://github.com/awslabs/amazon-kinesis-client#release-notes

**Comment by pfifer** [comment]
Version 1.4.0 uses a newer version of the KCL.  Please let us know if you have any other questions.

**Comment by whummer** [comment]
Thanks!
