### ISSUE TITLE
sample app regionName property is ignored

### ISSUE THREAD

**Issue by mccomplete** [awslabs/amazon-kinesis-client-python#4]
I set regionName to eu-central-1 and the daemon wasn't finding my stream.  Then I tried setting kinesisEndpoint (I had to guess the name of this property, by the way) to https://kinesis.eu-central-1.amazonaws.com and it found the stream.

**Comment by grepsr** [comment]
I can confirm that this suggested workaround is working. 

Thanks!

**Comment by JumpeiArashi** [comment]
Hi.
I have a same issue in `ap-northeast-1` region. In this region, is cause of this problem same?

And I've resolved this problem by using `--region-name` argument at `sample_kinesis_wordputter.py` (not using `regionName = ap-notheast-1` in `sample.properties`).

**Comment by grepsr** [comment]
Yes its the same problem. The older version do not read the sample.properties file properly it seems. The solution mentioned by @knorwood is a good fix until the latest fix gets deployed into PIP.

Here was my solution:
pip install amazon_kclpy pyyaml
AWS_SDK_VERSION=`ls -1 | grep 'aws-java-sdk-\d*' | awk -F'-' '{ print $4 }'`
echo "Starting KCL, AWS_SDK_VERSION=${AWS_SDK_VERSION}"
MULTILANG_DAEMON_PATH=`python /home/kinesis/kcl/cmd_helper.py --print_command --java /usr/bin/java --properties /home/kinesis/kcl/app.properties --classpath /home/kinesis/aws-java-sdk-${AWS_SDK_VERSION}/lib/aws-java-sdk-${AWS_SDK_VERSION}.jar`
/bin/bash -c "${MULTILANG_DAEMON_PATH}"

**Comment by JumpeiArashi** [comment]
OK! Thanks.

**Comment by Cory-Bradshaw** [comment]
Closing this issue, as more recent releases have updated the AWS SDK to a version that supports this region.
