### ISSUE TITLE
Unable to use EC2ContainerCredentialsProviderWrapper in kinesis consumer

### ISSUE THREAD

**Issue by nextdoor-engineer** [awslabs/amazon-kinesis-client-python#43]
Inside ECS container, DefaultAWSCredentialsProviderChain is getting ECS host profile instead of the taskRoleArn provided in ECS task definition.

We are using amazon_kclpy client to consumer from a stream. Even if we use latest version of this (1.4.3), we have the issue. When I explicitly set AWSCredentialsProvider = EC2ContainerCredentialsProviderWrapper in properties file, I get the below error:
No credential providers specifiedjava com.amazonaws.services.kinesis.multilang.MultiLangDaemon <properties file>

It looks like this is because the below setup.py is referencing aws-java-sdk-core 1.11.14 here
https://github.com/awslabs/amazon-kinesis-client-python/blob/master/setup.py#L66

However, I see that EC2ContainerCredentialsProviderWrapper is release in 1.11.16 onwards only. 

Can you please update https://github.com/awslabs/amazon-kinesis-client-python/blob/master/setup.py to use latest version of aws-java-sdk-* jars?

**Comment by pfifer** [comment]
Version 1.4.4 has just been released that has version 1.11.115 of the AWS Java SDK.  

Please try it out, and reopen if you're still having any issues.
