### ISSUE TITLE
initialPositionInStream AT_TIMESTAMP

### ISSUE THREAD

**Issue by rigoneri** [awslabs/amazon-kinesis-client-python#62]
Is there a way to setup initialPositionInStream to AT_TIMESTAMP? Both TRIM_HORIZON and LATEST return some values when it first starts even if it has been processed already...
So I was hoping I could set AT_TIMESTAMP to now and get any new messages after that...

**Comment by acannon828** [comment]
What did you find here? I suspect my KCL workers are getting records via TRIM_HORIZON even when I've set initialPositionInStream to LATEST, but I'm not confident...
