### ISSUE TITLE
Not able to run the sample app

### ISSUE THREAD

**Issue by alpha-arpitjain** [awslabs/amazon-kinesis-client-python#79]
I am running the sample app using this command
``amazon_kclpy_helper.py --print_command --java /usr/bin/java --properties samples/sample.properties``

And the wordputter app provided along with samples.

I am able to successfully run the wordputter but not able to understand if the sample app is actually fetching the data or not?

Only changes which I have made in the sample app are
initialPositionInStream = LATEST in sample.properties file and adding two print statements in both the record processor functions.

The biggest challenge I am facing is there are no logs getting generated (Or may be they are but I just don't know where to look for them), which is making it even difficult to debug. Any sort of help is appreciated.

**Comment by alpha-arpitjain** [comment]
never mind. It worked after downgrading the java version to java-8 from java-9

**Comment by pfifer** [comment]
Thanks for reporting this.  We will look into verifying Java 9 support.
