### ISSUE TITLE
Version 2.0 Release downloads incorrect JAR files

### ISSUE THREAD

**Issue by dmasters19** [awslabs/amazon-kinesis-client-python#90]
Related to issue #84 (which appears have lost traction) it seems the most recent release of amazon_kclpy 2.0 broke my project because it is downloading outdated `jar` files. It results in the error `Could not find com.amazonaws.services.kinesis.multilang.MultiLangDaemon`

The issue can be manually fixed by removing all the jar files that are downloaded by default when the package is  installed, and then using the `python setup.py download_jars` in this repo's `README` to download the correct ones.  However, this is not a good solution.  In the meantime I have hardcoded my project to use version 1.5 instead.

**Comment by sahilpalvia** [comment]
On installing new python KCL, the `amazon_kcl_helper.py` scripts should create something similar to run

```
amazon_kclpy_helper.py --print_command -j "<JAVA>" -p "<PROPERTIES FILE>"
<JAVA> -cp <PATH TO JARS> software.amazon.kinesis.multilang.MultiLangDaemon --properties-file <PROPERTIES FILE> 
```

As you see the new 2.0 version uses the 2.0 version of the java KCL. In the 2.0 version of the java KCL `com.amazonaws.services.kinesis.multilang.MultilangDaemon` no longer exists. The new MultiLangDaemon location is at `software.amazon.kinesis.multilang.MultiLangDaemon`.

Closing out the issue, please feel free to reopen if problem persists.
